about_me/urls.py
'''
Created on Sep 26, 2021

@author: cristian
'''
from django.urls import path
from . import views

app_name = "about_me"
urlpatterns = [
    path("", views.about_me, name = "about_me"),
    ]

front_page/urls.py
'''
Created on Sep 25, 2021

@author: cristian
'''
from django.urls import path
from . import views

app_name = "front_page"
urlpatterns = [
    path("", views.front_page, name="front_page"),
    ]

my_web/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('front_page.urls')),
    path('web_projects/', include('web_projects.urls')),
    path('todo_list/', include("todo_list.urls")),
] 

todo_list/urls.py
'''
Created on Oct 4, 2021

@author: cristian
'''
from django.urls import path
from . import views

app_name = "todo_list"

urlpatterns = [
    path("", views.ToDoListView.as_view(), name='todo_list'),
    path("task_confirm_delete/<int:pk>/", views.TaskDeleteView.as_view(), name="task_delete_view"),
    path("task_add_new_task/", views.TaskCreateView.as_view(), name="add_task"),
    ]

web_projects/urls.py
'''
Created on Oct 3, 2021

@author: cristian
'''
from django.urls import path
from . import views

app_name = "web_projects"

urlpatterns = [
    path("", views.web_projects, name="z"),
    ]

todo_list/models.py
from django.db import models

# Create your models here.
class ToDoList (models.Model):
    task = models.CharField(max_length=300)
    completed = models.BooleanField(default=False)
    
    def __str__(self):
        return self.task

web_projects/models.py
from django.db import models

# Create your models here.

todo_list/forms.py
'''
Created on Oct 4, 2021

@author: cristian
'''
from django import forms
from django.forms import ModelForm
from .models import ToDoList 

class ToDoListForm(ModelForm):
    completed = forms.BooleanField(widget=forms.CheckboxInput(),required=False, label="completed")
    
    class Meta:
        model = ToDoList
        fields = '__all__'

front_page/views.py
from django.shortcuts import render

# Create your views here.
def front_page(request):
    return render(request, "front_page/front_page.html")

todo_list/views.py
from django.views.generic import ListView, View
from .models import ToDoList
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse_lazy
from .forms import ToDoListForm
from django.contrib import messages


class ToDoListView(ListView):
    context_object_name = 'todo_list'
    template_name = "todo_list/todo_list.html"
    queryset = ToDoList.objects.all()
    
class TaskCreateView(View):
    template = "todo_list/todo_list_form.html"
    success_url = reverse_lazy("todo_list:todo_list")
    
    def get(self, request):
        task_form = ToDoListForm()
        return render(request, self.template, {"form": task_form})
    
    def post(self, request):
        if request.method == "POST":
            task_form = ToDoListForm(request.POST)
            
            if task_form.is_valid():
                task_form = task_form.save()
                messages.success(request, "Task added successfully")
            else:
                return redirect("todo_list:todo_list")
        return redirect(self.success_url)
    
    
class TaskDeleteView(View):
    model = ToDoList
    template = "todo_list/task_delete_view.html"
    success_url = reverse_lazy("todo_list:todo_list")
    
    def get(self, request, pk):
        task = get_object_or_404(self.model, pk=pk)
        return render(request, self.template, {"task": task})
    
    def post(self, request, pk):
        task = get_object_or_404(self.model, pk=pk)
        task.delete()
        return redirect(self.success_url)

web_projects/views.py
from django.shortcuts import render

# Create your views here.
def web_projects(request):
    return render(request, "web_projects/web_projects.html")

front_page/templates/front_page/footer.html
{% block footer %}

<div class="footer">
	<p>Please be patient, this is a work in progress.</p>
</div>

{% endblock %}

front_page/templates/front_page/front_page.html
{% extends "front_page/layout.html" %}
	
{% block content %}	
	<div class="short-explain">
		<p>
			This Website was built to train and show some features I'm able to develop.</br>
			I'll be adding new ones from time to time. I hope you enjoy it. 
		</p>
	</div>
	
	<div class="main-features">
		<h3>Why are you here?</h3>
		
		<p><a role="button" href="{% url 'web_projects:z' %}">My Web-App Projects</a></p>
		<p><a role="button" href="{% url 'todo_list:todo_list' %}">ToDo List</a></p>
	</div>
{% endblock %}

front_page/templates/front_page/layout.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

	<meta charset="UTF-8">
	
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	
	<link rel="stylesheet" type="text/css" href="{% static 'front_page/css/styles.css' %}">
	
	<title>Cristian Estevez's Portfolio</title>
	
	{% block head %}
	
	{% endblock %}
	
</head>
<body class="container">
	{% include './navbar.html' %}
	
	
	<div class="main-block">		

	{% block content %}

	{% endblock %}

	
	
	</div>
	{% include './footer.html' %}
</body>
</html>

front_page/templates/front_page/navbar.html
{% block header %}
	<div class="container container-title">
		<h1><a href="{% url 'front_page:front_page' %}">Cristian's Portfolio</a></h1>
	</div>
{% endblock %}

todo_list/templates/todo_list/task_delete_view.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
	<div>
		<form action="" method="post">
			{% csrf_token %}
			
			<input type="submit" value="Delete Permanently">
			<input type="submit" value="Cancel" onclick="window.location='{% url 'todo_list:todo_list' %}' ; return false;">
		</form>
	</div>
</body>
</html>

todo_list/templates/todo_list/todo_list.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
	{% for task in todo_list %}
		
		<p>{{ task }} <input type="checkbox" value="{{ task }}"></p> 
		<a href="{% url 'todo_list:task_delete_view' pk=task.id %}" title="Eliminar">Delete</a>
		
	{% endfor %}
	
	<p><a href="{% url 'todo_list:add_task' %}">Add new Task</a></p>
	
</body>
</html>

todo_list/templates/todo_list/todo_list_form.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
	<form method="post"> {% csrf_token %}
		<p>New Task: {{ form.as_table }}</p>
		<input type="submit" value="Save">
	</form>
</body>
</html>

web_projects/templates/web_projects/web_projects.html
{% extends 'front_page/layout.html' %}
{% load static %}	

{% block head %}
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Permanent+Marker&display=swap" rel="stylesheet">
{% endblock %}

{% block content %}

	<div class="web-projects">
		<div class="web-projects-carr-title">		
			<p>
				Layca Indumentaria
			</p>
		</div>
		
		<div class="web-projects-carr-container">
			
			<a href="{% static 'web_projects/img/laycaverdeblanco.png' %}"><img alt="layca page image screenshot" src="{% static 'web_projects/img/laycaverdeblanco.png' %}"></a>
		</div>
		
		<div class="web-projects-carr-footer">
			<p>You can visit the actual page in production clicking <a style="color:blue;" target="blank" href="https://layca.pythonanywhere.com/">"Here"</a>.</p>
			<div class="brief">
				<p>
					explain
				</p>
			</div>
		</div>
	</div>

{% endblock %}